apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: tilt-tests
  name: tilt-node-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: tilt-node-app
  labels:
    app: mocked-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mocked-api
  template:
    metadata:
      labels:
        app: mocked-api
    spec:
      containers:
        - name: mocked-api
          image: brunopadz/node-mocked-api
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: tilt-node-app
  labels:
    app: node-app
spec:
  selector:
    app: mocked-api
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
